[package]
name = "container_use_mcp"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/container_use_mcp.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
schemars = "0.8"
zed_extension_api = "0.5.0"
