id = "container-use-mcp"
name = "Container Use MCP Server"
description = "Containerized environments for coding agents."
version = "0.1.0"
schema_version = 1
authors = ["Agus Zubiaga <agus@zed.dev>", "Danilo Leal <danilo@zed.dev>"]
repository = "https://github.com/danilo-leal/zed-container-use-mcp"

[[capabilities]]
kind = "process:exec"
command = "which"
args = ["cu"]

[context_servers.container-use-mcp]
name = "Container Use MCP Server"
